language: cpp
before_install:
  - wget ftp://mirrors.kernel.org/sourceware/cygwin/x86/release/fftw3/libfftw3-devel/libfftw3-devel-3.3.3-1.tar.bz2
  - wget ftp://mirrors.kernel.org/sourceware/cygwin/x86/release/fftw3/libfftw3_3/libfftw3_3-3.3.3-1.tar.bz2
  - wget ftp://mirrors.kernel.org/sourceware/cygwin/x86/release/boost/libboost1.53/libboost1.53-1.53.0-2.tar.bz2
  - wget ftp://mirrors.kernel.org/sourceware/cygwin/x86/release/boost/libboost-devel/libboost-devel-1.53.0-2.tar.bz2
install: 
  - sudo apt-get update
  - sudo apt-get install mingw32
  - pushd .
  - TBZ2DIR=`pwd`
  - cd /usr/i586-mingw32msvc/
  - sudo tar jxf $TBZ2DIR/libfftw3-devel-*.tar.bz2
  - sudo tar jxf $TBZ2DIR/libfftw3_3-*.tar.bz2
  - sudo tar jxf $TBZ2DIR/libboost1.53-*.tar.bz2
  - sudo tar jxf $TBZ2DIR/libboost-devel-*.tar.bz2
  - popd
before_script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake-modules/mingw32-cross-compile.cmake
script:
  - make
after_script:
  - cpack -G TGZ
  - file ./apps/*
  - /usr/bin/i586-mingw32msvc-objdump -x ./apps/waveform-compare.exe | grep "DLL Name"
  - /usr/bin/i586-mingw32msvc-objdump -x ./apps/sound-match.exe | grep "DLL Name"
  - /usr/bin/i586-mingw32msvc-objdump -x ./apps/overlap-analysis.exe | grep "DLL Name"
  - cp `find -name "cygboost_program_options-mt-1_53.dll" -type f /usr/i586-mingw32msvc/"` .
  - cp `find -name "cygfftw3-3.dll" -type f /usr/i586-mingw32msvc/"` .