language: cpp
before_install:
  - wget ftp://mirrors.kernel.org/sourceware/cygwin/x86/release/fftw3/libfftw3-devel/libfftw3-devel-3.3.3-1.tar.bz2
  - wget ftp://mirrors.kernel.org/sourceware/cygwin/x86/release/fftw3/libfftw3_3/libfftw3_3-3.3.3-1.tar.bz2
  - wget ftp://mirrors.kernel.org/sourceware/cygwin/x86/release/boost/libboost1.53/libboost1.53-1.53.0-2.tar.bz2
  - wget ftp://mirrors.kernel.org/sourceware/cygwin/x86/release/boost/libboost-devel/libboost-devel-1.53.0-2.tar.bz2
install: 
  - sudo apt-get update
  - sudo apt-get install mingw32
  - pushd .
  - TBZ2DIR=`pwd`
  - cd /usr/i586-mingw32msvc/
  - sudo tar jxf $TBZ2DIR/libfftw3-devel-*.tar.bz2
  - sudo tar jxf $TBZ2DIR/libfftw3_3-*.tar.bz2
  - sudo tar jxf $TBZ2DIR/libboost1.53-*.tar.bz2
  - sudo tar jxf $TBZ2DIR/libboost-devel-*.tar.bz2
  - popd
  # boost/fftw3 need cygwin1.dll from ftp://mirrors.kernel.org/sourceware/cygwin/x86/release/cygwin/cygwin-1.7.25-1.tar.bz2
  # and cyggcc_s-1.dll from ftp://mirrors.kernel.org/sourceware/cygwin/x86/release/gcc/libgcc1/libgcc1-4.7.3-1.tar.bz2
  # and cygstdc++-6.dll from ftp://mirrors.kernel.org/sourceware/cygwin/x86/release/gcc/libstdc++6/libstdc++6-4.7.3-1.tar.bz2
  # when using gcc<4.5 you might need libstdc++.dll from here: http://sourceforge.net/projects/mingw/files/MinGW/Base/gcc/Version4/gcc-4.8.1-4/gcc-c%2B%2B-4.8.1-4-mingw32-dll.tar.lzma/download
before_script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake-modules/mingw32-cross-compile.cmake
script:
  - make
after_script:
  - cpack -G TGZ
  - file ./apps/*
  - /usr/bin/i586-mingw32msvc-objdump -x ./apps/waveform-compare.exe | grep "DLL Name"
  - /usr/bin/i586-mingw32msvc-objdump -x ./apps/sound-match.exe | grep "DLL Name"
  - /usr/bin/i586-mingw32msvc-objdump -x ./apps/overlap-analysis.exe | grep "DLL Name"