language: objective-c
install: 
  - brew update
  - brew install boost
  - brew install fftw
  - brew install cmake
before_script:
  - mkdir build && cd build
  - cmake .. 
script:
  - make
after_script:
  - cpack -G TGZ
  - ./apps/overlap-analysis -h
  - ./apps/sound-match -h
  - ./apps/waveform-compare -h