language: objective-c
install: 
  - brew update
  - brew install boost
  - brew install fftw
  - brew install cmake
before_script:
  - mkdir build && cd build
  - cmake ..
script:
  - make package
after_script:
  - ./apps/overlap-analysis -h
  - ./apps/sound-match -h
  - ./apps/waveform-compare -h